# Generated by Django 5.0.6 on 2024-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Mobile"),
                    ("L", "Lapetop"),
                    ("TW", "Top Wear"),
                    ("BW", "Bottom Wear"),
                    ("S", "Shoes"),
                ],
                max_length=10,
            ),
        ),
    ]
