# Generated by Django 5.1.2 on 2024-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Afg', ' Afganistan'), ('Brz', 'Brazil'), ('Comb', 'Combodia'), ('Canada', 'Canada'), ('Eng', 'England'), ('Europe', 'Europe'), ('Florida', 'Florida'), ('Ind', 'India'), ('Jarisuelum', 'jarisuelum'), ('Labanon', 'Labanon'), ('Mongolia', 'Mongolia'), ('Malta', 'Malta'), ('Nepal', 'Nepal'), ('Oman', 'Oman'), ('Pak', 'Pakistan'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Uzbakistan', 'Uzbakistan')], max_length=50),
        ),
    ]
